### ISSUE TITLE
Is nestedSave used anywhere?

### ISSUE THREAD

**Issue by Whoaa512** [praece/sails-bookshelf#2]
Hey I'm trying to do a very trimmed down port of this to enable graph saves from my Base bookshelf model.

After looking through the code I don't see a reference to `nestedSave` anywhere except in the file itself, however the `graph.setup` and `graph.save` both reference `options.nested`.

Could you elaborate on what `options.nested` is actually used for and why `nestedSave` is not used anywhere?

**Comment by kevinob11** [comment]
Ah so the `nestedSave` file is from before I refactored, I need to remove it. Sorry that was likely _very_ confusing. `graphSave` is what you are looking for. `options.nested` is set to true for the models nested on the base model when they are saved. This allows me to know that they are nested so I don't commit the transaction I'm using for the full graphSave.

If you want to hop on hangouts or slack or something and discuss I'm more than happy to.

**Comment by Whoaa512** [comment]
Awesome thanks! That was really helpful. I think I have a solid implementation working now. If I get some time I'll post a gist with what I've got
